name: Build and Publish Domain & Contracts

on:
  push:
    branches:
      - main
    paths:
      - 'src/domain/**'
      - 'src/contracts/**'

jobs:
  build-and-publish-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Domain Dependencies
        run: npm i
        working-directory: src/domain

      - name: Build Domain
        run: npm run build
        working-directory: src/domain

      - name: Configure npm for publishing
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Version Domain
        run: npm version patch
        working-directory: src/domain

      - name: Publish Domain
        run: npm publish --access public
        working-directory: src/domain
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-and-publish-contracts:
    runs-on: ubuntu-latest
    needs: build-and-publish-domain
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Contracts Dependencies
        run: npm i
        working-directory: src/contracts

      - name: Build Contracts
        run: npm run build
        working-directory: src/contracts

      - name: Configure npm for publishing
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Version Contracts
        run: npm version patch
        working-directory: src/contracts

      - name: Publish Contracts
        run: npm publish --access public
        working-directory: src/contracts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
